### ISSUE TITLE
Red Hat

### ISSUE THREAD

**Issue by jamwilli** [doubleunion/opendiversitydata#57]
Update spelling, add link to released stats, and link to social. 

correct spelling: Red Hat 
data: http://www.redhat.com/en/about/blog/diversity-and-our-business
social: @RedHatNews or @RedHatJobs

**Comment by markmc** [comment]
Thanks @jamwilli !

Apologies @jalcine if you were still planning on submitting this

**Comment by jalcine** [comment]
[**@markmc**](https://github.com/markmc) commented on [Aug 20, 2015, 10:44 PM EDT](https://github.com/doubleunion/opendiversitydata/issues/57#issuecomment-133254565):

> Thanks @jamwilli !
> 
> Apologies @jalcine if you were still planning on submitting this

No worries, @markmc! I got more busy than expected.
